### ISSUE TITLE
Displaying certainty in Excel output?

### ISSUE THREAD

**Issue by jjuod** [smarsland/AviaNZ#44]
Not sure how to show certainty in the Excel outputs. Currently it is ignored and only the "species" field of the label is used to generate those outputs.

In addition, presence/absence sheets for the "Any sound" xls are not useful and could be removed.

**Comment by jjuod** [comment]
Also: displaying call types in Excel output?

**Comment by VirgyLis** [comment]
I think that a good idea could be to add a certainty column and to use the percentage that we have at the moment (0-50-100).

For the call types, it could be trickier. I think that there are 2 possible options: or we add a column or we save call type in a different file or sheet.

**Comment by Nirosha201** [comment]
How about the following for _species level excels_?
Sheet1: include 'certainty', no info about call type for v 2.0 but can introduce later
Sheet2: instead of Yes/No record the highest certainty in the file
Sheet3: instead of 0/1 record the highest certainty in the block

_Any_sound excels_
Sheet1: name the 6th column as 'species', include 'certainty'
Sheet2 and Sheet3: remove

**Comment by jjuod** [comment]
For now, removed extra sheets in "Any sound", and added the (highest) certainty info as suggested.

**Comment by jjuod** [comment]
Everybody seems to be satisfied with the current certainty export format, so closing this and will open a separate issue for dealing with call types.

**Comment by jjuod** [comment]
Export format change request: 1st page should repeat file name in every line of the output

**Comment by jjuod** [comment]
Fixed in  9cdbb444
